### ISSUE TITLE
ASSERT_EQUAL macros fail when input is a 'one-time' function.

### ISSUE THREAD

**Issue by MatthewPowley** [k-brac/CUTI#4]
The macro INTERNAL_CUTI_ASSERT_COMPARE uses the macro input 'bound' for creation of an information string and is passed to another macro IMPL_CUTI_ASSERT for the actual assertion.

If the caller used a 'one-time' function, e.g. an 'Initialize' function directly in a comparison macro then this would not execute correctly. The 'Initialize' function would be called twice, which situation depending might produce the wrong outcome or an unwanted exception.

class TestClass
{
public:
TestClass() : _initialized{false}
{}

int Initialize()
{
   if(_initialized) throw std::exception("Object already initialised")

   // Do some initialization and calculate a return value.
  return 1;
}

private:
  bool _initialized;
};

The some test code like this would fail.

`TestClass object;
CPPUNIT_ASSERT_EQUAL(1, object.Initialize());
`
The user could work around this by re-writing the test code as:
`
TestClass object;
auto const& initResult = object.Initialize();
CPPUNIT_ASSERT_EQUAL(1, initResult);
`

**Comment by k-brac** [comment]
good catch!
This should be fixed.
